# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27017:27017"
      restart: always
      volumes:
        - data:/data/db

  cloudsaws:
    image: cloudsaws
    build:
      args:
          buildconfig: Debug
      context: .
      dockerfile: Clouds_AWS/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb

